// Write a C program which will create child processes in the following tree format.

// Parent Process
//   /        \
// Child 1   Child 2
//             /  \
//         Child 3 Child 4

// Make sure that the output of print statement generated by various child and parent processes strictly following any one of the following sequence. 

// In Child 1 My id is ___ and my parent's id is _____.

// In Child 4 My id is ___ and my parent's id is _____.

// In Child 3 My id is ___ and my parent's id is _____.

// In Child 2 My id is ___ and my parent's id is _____.

// In Parent Process my id is ___ and my parent's id is _____.

//Name: M.Sri Sujan
//Roll No: CS21B1081

#include <stdio.h>
#include <unistd.h>    //for fork()
#include <sys/types.h>  //for pid_t
#include <sys/wait.h>   //for wait()

int main()
{
    pid_t pid1, pid2, pid3, pid4;    //pid_t is a data type which is capable of representing a process ID.
    pid1 = fork();      //1st fork() call to create child 1 for parent
    if (pid1 ==0){     //child 1
        printf("In Child 1 My id is %d and my parent's id is %d.\n", getpid(), getppid());
    }
    else if(pid1 > 0){  //parent
        pid2 = fork();  //2nd fork() call to create child 2 for parent
        if(pid2 == 0){  //child 2
            pid3 = fork();  //3rd fork() call to create child 3 for child 2
            if(pid3 == 0){   //child 3
                printf("In Child 3 My id is %d and my parent's id is %d.\n", getpid(), getppid());
            }
            else{  //child 2
                pid4 = fork();   //4th fork() call to create child 4 for child 2
                if(pid4 == 0){   //child 4
                    printf("In Child 4 My id is %d and my parent's id is %d.\n", getpid(), getppid());
                }
                else{   //child 2
                    wait(NULL);
                    wait(NULL);
                    printf("In Child 2 My id is %d and my parent's id is %d.\n", getpid(), getppid());
                }
            }
        } 
        else{  //parent
            wait(NULL);
            wait(NULL);
            printf("In Parent Process my id is %d and my parent's id is %d.\n", getpid(), getppid());
        }
    }
    return 0;
    
}
